### ISSUE TITLE
Features Tracking List (Propose suggestions here as comments)

### ISSUE THREAD

**Issue by tc-imba** [SSTIA/fun-portal#2]
This is a list of features to be added soon or in the future:

- [x] update log
- [x] Python 2/3 support
- [ ] run the code in a container
- [ ] human vs AI mode
- [ ] badges
- [ ] (maybe) other languages support

**Comment by TuXun1999** [comment]
Since I cannot build such a website by myself,  I have to turn in my codes without testing the efficiency of them. As a result, I will lose some rounds before I am fully aware of the shortcomings of my AI.
So, I suppose that perhaps there could be a simulating section? I can choose my opponent and have a virtual battle with him in the simulating section. But the result won't affect my scores in the game. It is just a way to test my codes and I don't have to sacrifice some of my scores to earn an improvement in my stupid AI...
p.s. also maybe giving us a recommendation website to test our codes is ok too....

**Comment by LukeXuan** [comment]
Actually it's not difficult to deploy the website on your own computer.

Please look at the deployment section of the `README.md` file.

As an alternative choice, a docker image can be provided I suggest.

**Comment by zyayoung** [comment]
Support Multithreading

Don't waste your 11 cores and keep us waiting!

**Comment by tc-imba** [comment]
> Support Multithreading
> 
> Don't waste your 11 cores and keep us waiting!

We should keep the match fair, so multi-threading is not permitted. If you create too many threads, other's program will have too less cpu time.

**Comment by zyayoung** [comment]
> > Support Multithreading
> > Don't waste your 11 cores and keep us waiting!
> 
> We should keep the match fair, so multi-threading is not permitted. If you create too many threads, other's program will have too less cpu time.

Sorry, I didn’t make it clear.
I mean we can run several matches or openings at the same time.

**Comment by tc-imba** [comment]
> > > Support Multithreading
> > > Don't waste your 11 cores and keep us waiting!
> > 
> > 
> > We should keep the match fair, so multi-threading is not permitted. If you create too many threads, other's program will have too less cpu time.
> 
> Sorry, I didn’t make it clear.
> I mean we can run several matches or openings at the same time.

This a config problem on the server, I've set 10 matches running together.
